package greta.speedymarket.model;
// Generated 19 sept. 2016 16:52:54 by Hibernate Tools 4.3.1



/**
 * TbClient generated by hbm2java
 */
public class TbClient  implements java.io.Serializable {


     private int idPersonne;
     private TbPersonne tbPersonne;

    public TbClient() {
    }

    public TbClient(TbPersonne tbPersonne) {
       this.tbPersonne = tbPersonne;
    }
   
    public int getIdPersonne() {
        return this.idPersonne;
    }
    
    public void setIdPersonne(int idPersonne) {
        this.idPersonne = idPersonne;
    }
    public TbPersonne getTbPersonne() {
        return this.tbPersonne;
    }
    
    public void setTbPersonne(TbPersonne tbPersonne) {
        this.tbPersonne = tbPersonne;
    }




}


