package greta.speedymarket.model;
// Generated 19 sept. 2016 16:52:54 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * TbCommande generated by hbm2java
 */
public class TbCommande  implements java.io.Serializable {


     private Integer idCommande;
     private TbPersonne tbPersonneByClientIdPers;
     private TbPersonne tbPersonneByPrepaIdPers;
     private TbStatut tbStatut;
     private Date CDate;
     private Date CDateretrait;
     private Set tbLigneCommandes = new HashSet(0);

    public TbCommande() {
    }

	
    public TbCommande(Date CDate) {
        this.CDate = CDate;
    }
    public TbCommande(TbPersonne tbPersonneByClientIdPers, TbPersonne tbPersonneByPrepaIdPers, TbStatut tbStatut, Date CDate, Date CDateretrait, Set tbLigneCommandes) {
       this.tbPersonneByClientIdPers = tbPersonneByClientIdPers;
       this.tbPersonneByPrepaIdPers = tbPersonneByPrepaIdPers;
       this.tbStatut = tbStatut;
       this.CDate = CDate;
       this.CDateretrait = CDateretrait;
       this.tbLigneCommandes = tbLigneCommandes;
    }
   
    public Integer getIdCommande() {
        return this.idCommande;
    }
    
    public void setIdCommande(Integer idCommande) {
        this.idCommande = idCommande;
    }
    public TbPersonne getTbPersonneByClientIdPers() {
        return this.tbPersonneByClientIdPers;
    }
    
    public void setTbPersonneByClientIdPers(TbPersonne tbPersonneByClientIdPers) {
        this.tbPersonneByClientIdPers = tbPersonneByClientIdPers;
    }
    public TbPersonne getTbPersonneByPrepaIdPers() {
        return this.tbPersonneByPrepaIdPers;
    }
    
    public void setTbPersonneByPrepaIdPers(TbPersonne tbPersonneByPrepaIdPers) {
        this.tbPersonneByPrepaIdPers = tbPersonneByPrepaIdPers;
    }
    public TbStatut getTbStatut() {
        return this.tbStatut;
    }
    
    public void setTbStatut(TbStatut tbStatut) {
        this.tbStatut = tbStatut;
    }
    public Date getCDate() {
        return this.CDate;
    }
    
    public void setCDate(Date CDate) {
        this.CDate = CDate;
    }
    public Date getCDateretrait() {
        return this.CDateretrait;
    }
    
    public void setCDateretrait(Date CDateretrait) {
        this.CDateretrait = CDateretrait;
    }
    public Set getTbLigneCommandes() {
        return this.tbLigneCommandes;
    }
    
    public void setTbLigneCommandes(Set tbLigneCommandes) {
        this.tbLigneCommandes = tbLigneCommandes;
    }




}


