package greta.speedymarket.model;
// Generated 19 sept. 2016 16:52:54 by Hibernate Tools 4.3.1



/**
 * TbLigneCommandeId generated by hbm2java
 */
public class TbLigneCommandeId  implements java.io.Serializable {


     private int idArticle;
     private int idCommande;

    public TbLigneCommandeId() {
    }

    public TbLigneCommandeId(int idArticle, int idCommande) {
       this.idArticle = idArticle;
       this.idCommande = idCommande;
    }
   
    public int getIdArticle() {
        return this.idArticle;
    }
    
    public void setIdArticle(int idArticle) {
        this.idArticle = idArticle;
    }
    public int getIdCommande() {
        return this.idCommande;
    }
    
    public void setIdCommande(int idCommande) {
        this.idCommande = idCommande;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TbLigneCommandeId) ) return false;
		 TbLigneCommandeId castOther = ( TbLigneCommandeId ) other; 
         
		 return (this.getIdArticle()==castOther.getIdArticle())
 && (this.getIdCommande()==castOther.getIdCommande());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdArticle();
         result = 37 * result + this.getIdCommande();
         return result;
   }   


}


